### ISSUE TITLE
Question: Have you attempted to sniff the 433MHz RF commands?

### ISSUE THREAD

**Issue by alisdairjsmyth** [devbobo/qmotion#1]
Great project.

I am looking to integrate with my QMotion motorised blinds but I am aiming to do so without a QSync device i.e. directly.  Have you attempted to sniff the RF signals transmitted from the standard remote?

**Comment by devbobo** [comment]
@alisdairjsmyth sorry about the delay with responding. I don't really have any equipment for sniffing RF signals, hence the reason I went down this track.

If you work something out, I'd be interested.
